with-expecter: true
dir: "mocks"
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

inpackage: false
outpkg: "mocks"

packages:
  github.com/vizurth/url_shortener:
    config:
      recursive: true
      all: true