volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:16
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U short -d short"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: short
      POSTGRES_PASSWORD: short
      POSTGRES_DB: short
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shortener

  shortener:
    build: .
    container_name: shortener
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      STORAGE_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: short
      POSTGRES_PASSWORD: short
      POSTGRES_DATABASE: short
      QUERY_SHORT_URL_BASE: "http://localhost:8080"
    ports:
      - "8080:8080"
    networks:
      - shortener

networks:
  shortener:
    driver: bridge
