volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:16
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U short -d short"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: short
      POSTGRES_PASSWORD: short
      POSTGRES_DB: short
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shortener

networks:
  shortener:
    driver: bridge