// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, shortCode
func (_m *MockURLService) Resolve(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockURLService_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockURLService_Expecter) Resolve(ctx interface{}, shortCode interface{}) *MockURLService_Resolve_Call {
	return &MockURLService_Resolve_Call{Call: _e.mock.On("Resolve", ctx, shortCode)}
}

func (_c *MockURLService_Resolve_Call) Run(run func(ctx context.Context, shortCode string)) *MockURLService_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_Resolve_Call) Return(originalURL string, err error) *MockURLService_Resolve_Call {
	_c.Call.Return(originalURL, err)
	return _c
}

func (_c *MockURLService_Resolve_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockURLService_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// ShortenURL provides a mock function with given fields: ctx, originalURL
func (_m *MockURLService) ShortenURL(ctx context.Context, originalURL string) (string, bool, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, originalURL)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockURLService_ShortenURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenURL'
type MockURLService_ShortenURL_Call struct {
	*mock.Call
}

// ShortenURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockURLService_Expecter) ShortenURL(ctx interface{}, originalURL interface{}) *MockURLService_ShortenURL_Call {
	return &MockURLService_ShortenURL_Call{Call: _e.mock.On("ShortenURL", ctx, originalURL)}
}

func (_c *MockURLService_ShortenURL_Call) Run(run func(ctx context.Context, originalURL string)) *MockURLService_ShortenURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_ShortenURL_Call) Return(shortCode string, isNew bool, err error) *MockURLService_ShortenURL_Call {
	_c.Call.Return(shortCode, isNew, err)
	return _c
}

func (_c *MockURLService_ShortenURL_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *MockURLService_ShortenURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
