// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(_a0 error) *MockStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func() error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, shortCode
func (_m *MockStorage) Resolve(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockStorage_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockStorage_Expecter) Resolve(ctx interface{}, shortCode interface{}) *MockStorage_Resolve_Call {
	return &MockStorage_Resolve_Call{Call: _e.mock.On("Resolve", ctx, shortCode)}
}

func (_c *MockStorage_Resolve_Call) Run(run func(ctx context.Context, shortCode string)) *MockStorage_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Resolve_Call) Return(_a0 string, _a1 error) *MockStorage_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Resolve_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockStorage_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, originalURL, shortCode
func (_m *MockStorage) Save(ctx context.Context, originalURL string, shortCode string) (string, bool, error) {
	ret := _m.Called(ctx, originalURL, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, error)); ok {
		return rf(ctx, originalURL, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, originalURL, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, originalURL, shortCode)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, originalURL, shortCode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
//   - shortCode string
func (_e *MockStorage_Expecter) Save(ctx interface{}, originalURL interface{}, shortCode interface{}) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", ctx, originalURL, shortCode)}
}

func (_c *MockStorage_Save_Call) Run(run func(ctx context.Context, originalURL string, shortCode string)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(_a0 string, _a1 bool, _a2 error) *MockStorage_Save_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(context.Context, string, string) (string, bool, error)) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
