postgres:
    host: "postgres"
    port: 5432
    username: "short"
    password: "short"
    database: "short"
    max_conns: 10
    min_conns: 1

query:
  http_addr: "0.0.0.0:8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 120s
  short_url_base: "http://localhost:8080"

storage:
  type: "postgres"